### ISSUE TITLE
Bug: Token refresh on embedded dashboards

### ISSUE THREAD

**Issue by bmtcril** [openedx/platform-plugin-aspects#23]
Currently the LMS embedded dashboards have their guest token timeout after a few minutes. After the timeout Superset will throw ugly errors until the user refreshes the page. The logs will state:

`superset-1  | 2024-04-03 16:32:21,199:warning:superset.security.manager:Invalid guest token`

We'll need to implement a token refresh to prevent this. Some similar issues:

https://github.com/apache/superset/issues/24666
https://github.com/apache/superset/issues/20817

**Comment by Ian2012** [comment]
There should be two endpoints:
- A one specific for the LMS instructor dashboard that verifies the user is an instructor and can only be called in the LMS with a proper CSRF token, loads the settings and returns a valid token using a code similar to this one: https://github.com/openedx/platform-plugin-aspects/blob/main/platform_plugin_aspects/extensions/filters.py#L38-L50
- A studio handler that does the same but for the current block settings.

This would prevent any external system from creating a valid guest token.

The template code and the `generate_guest_token` need to be updated so that it doesn't inject the token into the token so it's not passed to the JS runtime. Instead, a function needs to be created to fetch the guest token from a function that optionally receives an endpoint that defaults to the instructor dashboard endpoint and its overridden for the case of the XBlock.

@pomegranited Let me know if you have any questions or need any help
